import {notFound} from 'next/navigation';
import Link from 'next/link';
import {Check,ArrowUpRight} from 'lucide-react';
import {services,processSteps} from '@/data/services';
import {posts} from '@/data/posts';
import {PageHero} from '@/components/page-hero';
import {Button,JsonLd} from '@/components/ui';
import {Emergency} from '@/components/sections/emergency';
import {absolute,pageMeta} from '@/lib/seo';
import {company} from '@/lib/site-config';
export const dynamicParams=false;
export function generateStaticParams(){return services.map(s=>({slug:s.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(s=>s.slug===slug);return s?pageMeta(`İstanbul ${s.title} Hizmeti`,s.intro,`/hizmetler/${slug}`):{title:'Hizmet bulunamadı'}}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(s=>s.slug===slug);if(!s)notFound();const related=posts.filter(p=>p.service===slug);return <><PageHero eyebrow="ASTAF HİZMETLERİ" title={`İstanbul ${s.title} Hizmeti`} description={s.intro} crumbs={[{label:'Hizmetler',href:'/hizmetler'},{label:s.title,href:`/hizmetler/${s.slug}`}]}><div className="button-row"><Button href={`/servis-talebi?tur=${encodeURIComponent(s.label)}`}>{s.label} için talep oluştur</Button></div></PageHero><section className="section container content-grid"><article className="prose">{s.sections.map(c=><section key={c.title}><h2>{c.title}</h2><p>{c.text}</p></section>)}<h2>İnceleme ve uygulama başlıkları</h2><ul className="check-list">{s.checks.map(c=><li key={c}><Check size={18}/>{c}</li>)}</ul><h2>ASTAF hizmet süreci</h2><p>Talebinizi aldıktan sonra kapsamı belirlemek için gerekli bilgileri toplarız. Yerinde değerlendirme, teklif, uygulama ve teslim adımları birbirini izler. Sonraki bakım veya kontrol ihtiyacı ayrıca paylaşılır.</p><ol>{processSteps.map(([t,d])=><li key={t}><strong>{t}:</strong> {d}</li>)}</ol><h2>İstanbul’da hizmet planlaması</h2><p>İstanbul’daki bina ve işletmeler için hizmet kapsamı; konum, sistem özellikleri ve talep türüne göre belirlenir. İlçenizi ve asansör bilgilerinizi ileterek yerinde değerlendirme için talep oluşturabilirsiniz.</p><h2>Sık sorulan sorular</h2><div className="faq">{s.faq.map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</div>{related.length>0&&<><h2>İlgili rehberler</h2><div className="related-links">{related.map(p=><Link key={p.slug} href={`/blog/${p.slug}`}>{p.title}<ArrowUpRight size={18}/></Link>)}</div></>}</article><aside className="sidebar"><div className="sidebar-box"><h2>Yapınıza özel bir plan.</h2><p>Asansörünüzün durumunu ve ihtiyacınızı bize iletin. Bir sonraki adımı birlikte belirleyelim.</p><Button href={`/servis-talebi?tur=${encodeURIComponent(s.label)}`}>Teklif / servis talebi</Button></div><nav className="sidebar-box sidebar-nav" aria-label="Diğer hizmetler"><h2>Hizmetlerimiz</h2>{services.map(x=><Link aria-current={x.slug===slug?'page':undefined} key={x.slug} href={`/hizmetler/${x.slug}`}>{x.title}<ArrowUpRight size={15}/></Link>)}</nav></aside></section><Emergency/><JsonLd data={{'@context':'https://schema.org','@type':'Service',name:s.title,description:s.intro,url:absolute(`/hizmetler/${slug}`),serviceType:s.title,areaServed:{'@type':'City',name:'İstanbul'},provider:{'@type':'Organization',name:company.name,url:company.url||undefined}}}/><JsonLd data={{'@context':'https://schema.org','@type':'FAQPage',mainEntity:s.faq.map(f=>({'@type':'Question',name:f.q,acceptedAnswer:{'@type':'Answer',text:f.a}}))}}/></>}
