import {notFound} from 'next/navigation';
import Link from 'next/link';
import {posts} from '@/data/posts';
import {services} from '@/data/services';
import {PageHero} from '@/components/page-hero';
import {Button,JsonLd} from '@/components/ui';
import {absolute,pageMeta} from '@/lib/seo';
export const dynamicParams=false;
export function generateStaticParams(){return posts.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=posts.find(p=>p.slug===slug);if(!p)return {title:'Yazı bulunamadı'};const base=pageMeta(p.title,p.description,`/blog/${slug}`);return {...base,authors:[{name:p.author}],openGraph:{...base.openGraph,type:'article',publishedTime:p.published,modifiedTime:p.modified,authors:[p.author],images:[]},twitter:{...base.twitter,images:[]}}}
const date=(s:string)=>new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Istanbul'}).format(new Date(s));
export default async function Post({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=posts.find(p=>p.slug===slug);if(!p)notFound();const s=services.find(s=>s.slug===p.service)!;return <><PageHero eyebrow={p.category} title={p.title} description={p.description} crumbs={[{label:'Blog',href:'/blog'},{label:p.title,href:`/blog/${slug}`}]}><div className="article-meta"><span>{p.author}</span><span>Yayın: <time dateTime={p.published}>{date(p.published)}</time></span><span>Güncelleme: <time dateTime={p.modified}>{date(p.modified)}</time></span></div></PageHero><section className="section container content-grid"><article className="prose">{p.sections.map(c=><section key={c.title}><h2>{c.title}</h2><p>{c.text}</p></section>)}<h2>Binanıza özel değerlendirme</h2><p>Her sistemin koşulları farklıdır. <Link href={`/hizmetler/${s.slug}`}>{s.title}</Link> sayfamızda hizmet kapsamını inceleyebilir, mevcut sisteminiz için <Link href="/servis-talebi">servis talebi</Link> oluşturabilirsiniz.</p><p className="note-box">Bu rehber kullanıcı ve bina sorumlularını bilgilendirmek içindir; teknik müdahale talimatı değildir. Elektrik, mekanizma ve güvenlik bileşenleri üzerindeki işlemler teknik ekip tarafından yapılmalıdır.</p></article><aside className="sidebar"><div className="sidebar-box"><h2>{s.title}</h2><p>{s.short}</p><Button href={`/hizmetler/${s.slug}`}>Hizmeti incele</Button></div><div className="sidebar-box sidebar-nav"><h2>İlgili yazılar</h2>{posts.filter(x=>x.service===p.service&&x.slug!==p.slug).slice(0,3).map(x=><Link key={x.slug} href={`/blog/${x.slug}`}>{x.title}</Link>)}<Link href="/blog">Tüm rehberler</Link></div></aside></section><JsonLd data={{'@context':'https://schema.org','@type':'Article',headline:p.title,description:p.description,datePublished:p.published,dateModified:p.modified,author:{'@type':'Organization',name:p.author},publisher:{'@type':'Organization',name:'ASTAF Asansör'},mainEntityOfPage:absolute(`/blog/${slug}`)}}/></>}
